// /**
//  * src/Api/Organization/organizationApi.tsx
//  *
//  * All API functions for the Organization module.
//  * Matches exactly the Swagger endpoints provided:
//  *
//  *   POST /api/Organization/addUpdateOrganization
//  *   GET  /api/Organization/organizations
//  *   POST /api/Organization/GetorganizationById
//  *   POST /api/Organization/MakeorganizationActiveInactive
//  *   GET  /api/Organization/GetDashboardData
//  *   POST /api/Organization/organizationLogin
//  */

// const BASE = () => (import.meta.env.VITE_API_BASE_URL ?? "").replace(/\/$/, "");
// const API_KEY = () => import.meta.env.VITE_API_KEY ?? "";

// /* ─── Admin auth headers (used by admin-side org management) ─────── */
// const adminHeaders = (): HeadersInit => ({
//     "Content-Type": "application/json",
//     "X-API-KEY":    API_KEY(),
//     "X-ADMIN-CODE": localStorage.getItem("ADCODE") ?? "",
// });

// /* ─── Org auth headers (used after org login) ────────────────────── */
// const orgHeaders = (): HeadersInit => ({
//     "Content-Type": "application/json",
//     "X-API-KEY":    API_KEY(),
//     "X-ORG-CODE":   localStorage.getItem("ORGCODE") ?? "",
// });

// /* ─── Generic API response wrapper ──────────────────────────────── */
// export interface ApiResponse<T = any> {
//     responseCode:      number;
//     responseStatus:    boolean;
//     responseErrorType: string;
//     responseMessage:   string;
//     noOfRecord:        number;
//     data:              T;
// }

// /* ─── Organization record shape ──────────────────────────────────── */
// export interface OrganizationRecord {
//     Id:            number;
//     OrgCode:       string;
//     OrgName:       string;
//     Email:         string;
//     Mobile:        string;
//     Address?:      string;
//     City?:         string;
//     State?:        string;
//     Country?:      string;
//     PinCode?:      string;
//     Website?:      string;
//     LogoUrl?:      string;
//     IsActive:      boolean | "Y" | "N";
//     CreatedOn?:    string;
//     UpdatedOn?:    string;
//     AdminCode?:    number;
//     /* Dashboard fields (returned by GetDashboardData) */
//     TotalForms?:      number;
//     TotalResponses?:  number;
//     TotalConsents?:   number;
//     TotalGrievances?: number;
// }

// export interface OrgLoginPayload {
//     UserName: string;
//     Password: string;
//     OrgCode:  string;
// }

// export interface OrgLoginResponse {
//     OrgCode:   string;
//     OrgName:   string;
//     Email:     string;
//     Token?:    string;
// }

// export interface AddUpdateOrgPayload {
//     Id?:       number;        // omit for create, include for update
//     OrgName:   string;
//     Email:     string;
//     Mobile:    string;
//     Address?:  string;
//     City?:     string;
//     State?:    string;
//     Country?:  string;
//     PinCode?:  string;
//     Website?:  string;
//     Password?: string;        // required on create
//     OrgCode?:  string;        // generated by backend on create
// }

// export interface OrgListParams {
//     status?:       string;
//     pageNumber?:   number;
//     pageSize?:     number;
//     sortColumn?:   string;
//     sortOrder?:    "ASC" | "DESC";
//     startDate?:    string;
//     endDate?:      string;
//     searchColumn?: string;
//     searchString?: string;
// }

// /* ══════════════════════════════════════════════════════════════════
//    1. Organization Login
//    POST /api/Organization/organizationLogin  (multipart/form-data)
// ══════════════════════════════════════════════════════════════════ */
// export const organizationLogin = async (
//     payload: OrgLoginPayload
// ): Promise<ApiResponse<OrgLoginResponse>> => {
//     const fd = new FormData();
//     fd.append("UserName", payload.UserName);
//     fd.append("Password", payload.Password);
//     fd.append("OrgCode",  payload.OrgCode);

//     const res = await fetch(`${BASE()}/api/Organization/organizationLogin`, {
//         method: "POST",
//         headers: { "X-API-KEY": API_KEY() },   // no Content-Type for FormData
//         body: fd,
//     });
//     if (!res.ok) throw new Error(`Login failed: ${res.status}`);
//     const json: ApiResponse<OrgLoginResponse> = await res.json();
//     if (json.responseCode !== 101) throw new Error(json.responseMessage || "Login failed");
//     return json;
// };

// /* ══════════════════════════════════════════════════════════════════
//    2. Add / Update Organization
//    POST /api/Organization/addUpdateOrganization  (JSON)
// ══════════════════════════════════════════════════════════════════ */
// export const addUpdateOrganization = async (
//     payload: AddUpdateOrgPayload
// ): Promise<ApiResponse<OrganizationRecord>> => {
//     const res = await fetch(`${BASE()}/api/Organization/addUpdateOrganization`, {
//         method: "POST",
//         headers: adminHeaders(),
//         body: JSON.stringify(payload),
//     });
//     if (!res.ok) throw new Error(`Save failed: ${res.status}`);
//     const json: ApiResponse<OrganizationRecord> = await res.json();
//     if (json.responseCode !== 101) throw new Error(json.responseMessage || "Save failed");
//     return json;
// };

// /* ══════════════════════════════════════════════════════════════════
//    3. Get Organization List
//    GET /api/Organization/organizations  (query params)
// ══════════════════════════════════════════════════════════════════ */
// export const getOrganizationList = async (
//     params: OrgListParams = {}
// ): Promise<ApiResponse<string>> => {
//     // Backend returns data as JSON string — same pattern as Forms API
//     const qs = new URLSearchParams({
//         status:       params.status       ?? "Y",
//         PageNumber:   String(params.pageNumber  ?? 1),
//         PageSize:     String(params.pageSize    ?? 10),
//         SortColumn:   params.sortColumn   ?? "",
//         SortOrder:    params.sortOrder    ?? "DESC",
//         StartDate:    params.startDate    ?? "",
//         EndDate:      params.endDate      ?? "",
//         SearchColumn: params.searchColumn ?? "",
//         SearchString: params.searchString ?? "",
//     });

//     const res = await fetch(`${BASE()}/api/Organization/organizations?${qs}`, {
//         method: "GET",
//         headers: adminHeaders(),
//     });
//     if (!res.ok) throw new Error(`Fetch failed: ${res.status}`);
//     return res.json();
// };

// /* Helper: parse the stringified data from getOrganizationList */
// export const parseOrgList = (raw: ApiResponse<string>): OrganizationRecord[] => {
//     if (!raw.data) return [];
//     try {
//         return typeof raw.data === "string" ? JSON.parse(raw.data) : (raw.data as any);
//     } catch {
//         return [];
//     }
// };

// /* ══════════════════════════════════════════════════════════════════
//    4. Get Organization By Id
//    POST /api/Organization/GetorganizationById  (JSON body)
// ══════════════════════════════════════════════════════════════════ */
// export const getOrganizationById = async (
//     id: number
// ): Promise<OrganizationRecord | null> => {
//     const res = await fetch(`${BASE()}/api/Organization/GetorganizationById`, {
//         method: "POST",
//         headers: adminHeaders(),
//         body: JSON.stringify({ Id: id }),
//     });
//     if (!res.ok) throw new Error(`Fetch failed: ${res.status}`);
//     const json: ApiResponse<string> = await res.json();
//     if (json.responseCode !== 101) throw new Error(json.responseMessage || "Not found");

//     const rows: OrganizationRecord[] =
//         typeof json.data === "string" ? JSON.parse(json.data) : (json.data as any) ?? [];
//     return rows[0] ?? null;
// };

// /* ══════════════════════════════════════════════════════════════════
//    5. Make Organization Active / Inactive
//    POST /api/Organization/MakeorganizationActiveInactive  (JSON body)
// ══════════════════════════════════════════════════════════════════ */
// export const toggleOrgStatus = async (
//     id: number,
//     isActive: boolean
// ): Promise<ApiResponse> => {
//     const res = await fetch(`${BASE()}/api/Organization/MakeorganizationActiveInactive`, {
//         method: "POST",
//         headers: adminHeaders(),
//         body: JSON.stringify({ Id: id, IsActive: isActive }),
//     });
//     if (!res.ok) throw new Error(`Toggle failed: ${res.status}`);
//     const json: ApiResponse = await res.json();
//     if (json.responseCode !== 101) throw new Error(json.responseMessage || "Toggle failed");
//     return json;
// };

// /* ══════════════════════════════════════════════════════════════════
//    6. Get Dashboard Data  (for OrganizationDashboard page)
//    GET /api/Organization/GetDashboardData  (no params — uses X-ORG-CODE header)
// ══════════════════════════════════════════════════════════════════ */
// export interface OrgDashboardData {
//     TotalForms?:      number;
//     TotalResponses?:  number;
//     TotalConsents?:   number;
//     TotalGrievances?: number;
//     PendingWithdrawals?: number;
//     OrgName?:         string;
//     OrgCode?:         string;
//     RecentActivity?:  any[];
// }

// export const getOrgDashboardData = async (): Promise<OrgDashboardData> => {
//     const res = await fetch(`${BASE()}/api/Organization/GetDashboardData`, {
//         method: "GET",
//         headers: orgHeaders(),
//     });
//     if (!res.ok) throw new Error(`Dashboard fetch failed: ${res.status}`);
//     const json: ApiResponse<OrgDashboardData | string> = await res.json();
//     if (json.responseCode !== 101) throw new Error(json.responseMessage || "Failed");

//     const data = typeof json.data === "string" ? JSON.parse(json.data) : json.data;
//     return (Array.isArray(data) ? data[0] : data) ?? {};
// };